create database Hospital_Managment 
use Hospital_Managment

--creating department table
create table department(D_NAME  VARCHAR(50) UNIQUE ,D_LOCATION VARCHAR(60),FACILITIES VARCHAR(80))
--CREATING TABLE FOR DOCTORS
CREATE TABLE ALL_DOCTORS(DOC_NO INT UNIQUE,DEPARTMENT VARCHAR (50) FOREIGN KEY REFERENCES DEPARTMENT(D_NAME))
--CREATING TABLE FOR REGULAR DOCTORS
CREATE TABLE DOC_REG(DOC_NO INT FOREIGN KEY REFERENCES ALL_DOCTORS(DOC_NO) , D_NAME VARCHAR(50),QUALIFICATION VARCHAR(50),SALARY INT,EN_TIME TIME,EX_TIME TIME,ADDRESS1 VARCHAR(50),PH_NO INT,DOJ DATE)
--CREATING TABLE FOR CALL ON DOTOR
CREATE TABLE DOC_ON_CALL(DOC_NO INT FOREIGN KEY REFERENCES ALL_DOCTORS(DOC_NO) , D_NAME VARCHAR(50),QUALIFICATION VARCHAR(50),FS_PR_CL INT,PYMT_DU INT,ADDRESS1 VARCHAR(50),PH_NO INT)
--CREATING PAT_ENTRY
CREATE TABLE PAT_ENTRY(PATNO INT PRIMARY KEY, PAT_NAME VARCHAR(5), CHKUP_DT VARCHAR(50), PT_AGE INT, SEX VARCHAR(10) DEFAULT 'M', RFRG_CSTNT VARCHAR(50),
			DIAGNOSIS VARCHAR(50), RFD VARCHAR(50),ADDRESS1 VARCHAR(50), CITY VARCHAR(50), PH_NO INT, DEPARTMENT VARCHAR(50))
--CREATING PAT CHKUP
CREATE TABLE PAT_CHKUP (PAT_NO INT FOREIGN KEY REFERENCES PAT_ENTRY(PATNO), DOC_NO INT FOREIGN KEY REFERENCES ALL_DOCTORS(DOC_NO), DIAGNOSIS VARCHAR(50), STATUS1 VARCHAR(50), TREATMENT VARCHAR (50))
--CREATING PATADMIT 
CREATE TABLE PAT_ADMIT (PAT_NO INT FOREIGN KEY REFERENCES PAT_ENTRY(PATNO) , ADV_PYMT INT , MODE_PYMT VARCHAR(50), ROOM_NO INT , DEPTNAME VARCHAR(50) FOREIGN KEY REFERENCES DEPARTMENT(D_NAME), ADMITO_ON INT, COND_ON VARCHAR(50),INVSTGTN_DN varchar(50), TRMT_SDT varchar(50), ATTDNT_NM int)
--CREATING PAT DIS
CREATE TABLE PAT_DIS(PAT_NO INT FOREIGN KEY REFERENCES PAT_ENTRY(PATNO), TR_ADVS VARCHAR(50), TR_GVN VARCHAR(50), MEDICINES VARCHAR(50), PYMT_GV INT, DIS_ON INT)
--CREATING PAT REG
CREATE TABLE PAT_REG(PAT_NO INT FOREIGN KEY REFERENCES PAT_ENTRY(PATNO), DATE_VIS DATE, CONDITION VARCHAR(50), TREATMENT VARCHAR(50), MEDICINES VARCHAR(50), DOC_NO INT, PAYMT INT)
--CREATING PAT_OPR
CREATE TABLE PAT_OPR(PAT_NO INT FOREIGN KEY REFERENCES PAT_ENTRY(PATNO) , DATE_OPR DATE , IN_COND VARCHAR(50), AFOP_COND VARCHAR(50), TY_OPERATION VARCHAR(50), MEDICINES VARCHAR(50), DOC_NO INT FOREIGN KEY REFERENCES ALL_DOCTORS(DOC_NO),OPTH_NO INT, OTHER_SUG VARCHAR(50))
--CREATING ROOM DETAILS

CREATE TABLE ROOM_DETAILS (ROOM_NO INT UNIQUE, TYPE1 VARCHAR(50), STATUS1 VARCHAR(50), RM_DL_CRG INT, OTHER_CRG INT)


